"""CMake configure/build helpers for FVP orchestration."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import List, Optional, Set

from .env import REPO_ROOT
from .errors import FvpScriptError


def _clear_stale_gcda(build_dir: Path) -> None:
    """Remove leftover .gcda files so a rebuild can never desync from stale
    coverage data. Recompiling a source file regenerates its .gcno with a
    new stamp; an old .gcda left next to it causes gcov to abort with
    'stamp mismatch with notes file'. Any real coverage is regenerated by
    the FVP run(s) that follow and re-merged via merge-stream, so it's safe
    to drop existing .gcda here.
    """
    if not build_dir.exists():
        return
    for gcda in build_dir.rglob("*.gcda"):
        gcda.unlink(missing_ok=True)


def read_cmake_cache_path(build_dir: Path, key: str) -> Optional[Path]:
    cache = build_dir / "CMakeCache.txt"
    if not cache.exists():
        return None
    prefix = f"{key}:PATH="
    for line in cache.read_text(errors="ignore").splitlines():
        if line.startswith(prefix):
            value = line[len(prefix):].strip()
            if value:
                return Path(value).resolve()
    return None


def manifest_test_names(generated_tests_dir: Optional[Path]) -> Optional[Set[str]]:
    """Return the set of test-case names in a generated-tests ``manifest.json``,
    or ``None`` when there is no usable manifest to constrain against.

    Keeps build/run keyed to the *active* filter: a filtered run
    (``--float-precision``, ``--name``, ``--limit``, ...) rewrites the manifest
    to its own entries, but stale ``*.elf`` files from an earlier, wider run can
    still sit in the build tree (CMake does not delete the output of a target it
    no longer defines). ``None`` preserves the historical "use whatever is on
    disk" behaviour for callers with no manifest (e.g. ``--skip-generation``).
    """
    if generated_tests_dir is None:
        return None
    manifest_path = Path(generated_tests_dir) / "manifest.json"
    if not manifest_path.exists():
        return None
    try:
        manifest = json.loads(manifest_path.read_text())
    except (OSError, ValueError):
        return None
    names = {str(entry["name"]) for entry in manifest.get("tests", []) if entry.get("name")}
    return names or None


def _prune_stale_test_elves(
    build_dir: Path, allowed_names: Optional[Set[str]], verbosity: int = 0
) -> List[Path]:
    """Delete ``build_dir/tests/**/*.elf`` files whose stem is not in the active
    run's manifest, so a filtered rebuild in a tree a wider run already built
    does not leave excluded-case binaries behind for ELF discovery or the
    descriptor-aware reporting pass to pick up. No-op when ``allowed_names`` is
    ``None`` (no manifest to judge against). See issue #66.
    """
    tests_dir = build_dir / "tests"
    if allowed_names is None or not tests_dir.exists():
        return []
    removed: List[Path] = []
    for elf in tests_dir.rglob("*.elf"):
        if elf.is_file() and elf.stem not in allowed_names:
            elf.unlink()
            removed.append(elf)
    if removed and verbosity >= 1:
        print(f"Pruned {len(removed)} stale test ELF(s) outside the active filter under {tests_dir}")
    return removed


def cmake_configure(
    source_dir: Path,
    build_dir: Path,
    toolchain_file: Path,
    cpu: str,
    cmsis5: Path,
    optimization: str,
    extra_defs: List[str],
    generator: Optional[str],
    generated_tests_dir: Optional[Path],
    enable_coverage: bool,
    verbosity: int,
    env: dict,
) -> None:
    build_dir.mkdir(parents=True, exist_ok=True)

    cmake_cache = build_dir / "CMakeCache.txt"
    if cmake_cache.exists():
        cmake_cache.unlink()

    if enable_coverage:
        _clear_stale_gcda(build_dir)

    _prune_stale_test_elves(build_dir, manifest_test_names(generated_tests_dir), verbosity)

    cmd = [
        "cmake",
        "-S", str(source_dir),
        "-B", str(build_dir),
        f"-DCMAKE_TOOLCHAIN_FILE={toolchain_file}",
        f"-DTARGET_CPU={cpu}",
        f"-DCMSIS_PATH={cmsis5}",
        f"-DCMSIS_OPTIMIZATION_LEVEL={optimization}",
    ] + [f"-D{item}" for item in extra_defs]
    if generated_tests_dir is not None:
        cmd.append(f"-DGENERATED_TESTS_DIR={generated_tests_dir}")
    if enable_coverage:
        cmd.append("-DENABLE_COVERAGE=ON")

    if generator:
        cmd += ["-G", generator]
    if verbosity >= 2:
        print(f"Configure: {' '.join(cmd)}")
    stdout = subprocess.DEVNULL if verbosity <= 1 else None
    rc = subprocess.call(cmd, cwd=str(REPO_ROOT), env=env, stdout=stdout, stderr=None)
    if rc != 0:
        raise FvpScriptError(f"CMake configure failed for {cpu} (rc={rc})")


def cmake_build(build_dir: Path, verbosity: int, env: dict, jobs: Optional[int]) -> None:
    cmd = ["cmake", "--build", str(build_dir)]
    if jobs and jobs > 0:
        cmd += ["--", f"-j{jobs}"]
    if verbosity >= 2:
        print(f"Build: {' '.join(cmd)}")
    stdout = subprocess.DEVNULL if verbosity <= 1 else None
    rc = subprocess.call(cmd, cwd=str(REPO_ROOT), env=env, stdout=stdout, stderr=None)
    if rc != 0:
        raise FvpScriptError(f"CMake build failed (rc={rc})")


def find_elves(build_dir: Path, allowed_names: Optional[Set[str]] = None) -> List[Path]:
    tests_dir = build_dir / "tests"
    root = tests_dir if tests_dir.exists() else build_dir
    elves = [path for path in root.rglob("*.elf") if path.is_file()]
    if allowed_names is not None:
        elves = [path for path in elves if path.stem in allowed_names]
    return elves
