"""Per-case reuse stamps for the generation step.

TFLite conversion plus interpreter inference dominates generation wall time, and
every input that can change a case's emitted bytes is knowable before that work
starts: the descriptor document, the per-case generation inputs (cpu, suite,
float precision, seed) and the generator itself. A stamp folds all of those into
one digest; a case whose on-disk stamp still matches is reused verbatim. See
issue #107.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path
from typing import Any, Dict, Iterator, Optional

from helia_core_tester.core.discovery import find_repo_root, find_tester_templates_dir

STAMP_FILENAME = ".stamp"

# Version prefix of the stamp payload itself. Bump when the payload layout
# changes so old stamps cannot accidentally validate against new semantics.
_STAMP_SCHEMA = "helia-core-tester/generation-stamp/1"

# Packages whose codegen or numerics feed the emitted bytes; a version bump in
# either can change a converted model or a reference output.
_PINNED_PACKAGES = ("tensorflow", "ai-edge-litert")

_version_hash_cache: Optional[str] = None


def _iter_generator_sources() -> Iterator[Path]:
    """Files whose content defines what the generator emits for any case.

    Descriptors are deliberately excluded: they are hashed into each case's own
    stamp, so folding them in here as well would make one descriptor edit
    invalidate every other case.
    """
    generation_root = Path(__file__).resolve().parent
    for path in sorted(generation_root.rglob("*.py")):
        if "__pycache__" in path.parts:
            continue
        yield path

    try:
        templates_root = find_tester_templates_dir()
    except Exception:
        return
    if not templates_root.exists():
        return
    for path in sorted(templates_root.rglob("*")):
        if path.is_file() and "__pycache__" not in path.parts:
            yield path


def _pinned_package_versions() -> Dict[str, str]:
    from importlib import metadata

    versions: Dict[str, str] = {}
    for package in _PINNED_PACKAGES:
        try:
            versions[package] = metadata.version(package)
        except Exception:
            versions[package] = "unavailable"
    return versions


def generator_version_hash() -> str:
    """Digest of the generator sources, templates and pinned converter versions.

    Cached for the process: the inputs cannot change under a running generation.
    """
    global _version_hash_cache
    if _version_hash_cache is not None:
        return _version_hash_cache

    digest = hashlib.sha256()
    digest.update(_STAMP_SCHEMA.encode("utf-8"))
    try:
        repo_root = find_repo_root()
    except Exception:
        repo_root = None
    for path in _iter_generator_sources():
        try:
            label = str(path.relative_to(repo_root)) if repo_root else path.name
        except ValueError:
            label = path.name
        digest.update(label.encode("utf-8"))
        digest.update(b"\0")
        digest.update(hashlib.sha256(path.read_bytes()).digest())
    digest.update(
        json.dumps(_pinned_package_versions(), sort_keys=True).encode("utf-8")
    )
    _version_hash_cache = digest.hexdigest()
    return _version_hash_cache


def case_stamp(
    descriptor: Dict[str, Any],
    *,
    case_name: str,
    cpu: str,
    suite: str,
    float_precision: str,
    seed: int,
    version_hash: str,
) -> str:
    """Digest of everything that determines a case's generated bytes."""
    payload = {
        "schema": _STAMP_SCHEMA,
        "descriptor": descriptor,
        "case_name": case_name,
        "cpu": cpu,
        "suite": suite,
        "float_precision": float_precision,
        "seed": seed,
        "generator_version": version_hash,
    }
    encoded = json.dumps(payload, sort_keys=True, default=str).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def read_stamp(test_dir: Path) -> Optional[str]:
    stamp_path = test_dir / STAMP_FILENAME
    try:
        return stamp_path.read_text().strip()
    except OSError:
        return None


def write_stamp(test_dir: Path, stamp: str) -> None:
    """Record a case as reusable. Must be the last write of a case."""
    (test_dir / STAMP_FILENAME).write_text(stamp + "\n")


def clear_stamp(test_dir: Path) -> None:
    """Invalidate a case before regenerating it.

    A crash partway through regeneration must not leave the previous run's
    stamp standing over half-written files.
    """
    (test_dir / STAMP_FILENAME).unlink(missing_ok=True)


def case_artifacts_present(test_dir: Path, case_name: str) -> bool:
    """Cheap integrity check that a stamped case is still whole on disk."""
    if not (test_dir / "descriptor.yaml").is_file():
        return False
    if (test_dir / f"{case_name}.tflite").is_file():
        return True
    if any(test_dir.glob("*.c")):
        return True
    includes_dir = test_dir / "includes"
    return includes_dir.is_dir() and any(includes_dir.glob("*.h"))


def prune_unlisted_cases(generated_tests_dir: Path, keep_relative_dirs: set[str]) -> int:
    """Delete case directories outside the current run's set.

    Generation used to wipe the whole output tree on every run, which made the
    tree an exact record of the active filter. Reuse means the tree survives, so
    the pruning has to be explicit or a narrower run would leave a wider run's
    cases behind for build and run steps to pick up.
    """
    removed = 0
    keep = {str(Path(item)) for item in keep_relative_dirs}
    for family_dir in sorted(generated_tests_dir.iterdir()):
        if not family_dir.is_dir():
            continue
        for case_dir in sorted(family_dir.iterdir()):
            if not case_dir.is_dir():
                continue
            relative = str(case_dir.relative_to(generated_tests_dir))
            if relative in keep:
                continue
            shutil.rmtree(case_dir, ignore_errors=True)
            removed += 1
        if not any(family_dir.iterdir()):
            family_dir.rmdir()
    return removed
