#!/usr/bin/env python3
"""Generate a compile-time symbol reference table for CMSIS-NN public APIs."""

from __future__ import annotations

import argparse
import re
import subprocess
from pathlib import Path

_FUNC_RE = re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_\s\*]*\s+(arm_[A-Za-z0-9_]+)\s*\(")
_NM_RE = re.compile(r"^[0-9A-Fa-f]+\s+[A-Za-z]\s+(arm_[A-Za-z0-9_]+)$")


def _collect_symbols(header: Path) -> list[str]:
    symbols: list[str] = []
    seen: set[str] = set()
    for line in header.read_text(encoding="utf-8").splitlines():
        match = _FUNC_RE.match(line)
        if match is None:
            continue
        symbol = match.group(1)
        if symbol not in seen:
            seen.add(symbol)
            symbols.append(symbol)
    return symbols


def _symbol_enabled(symbol: str, *, enable_f32: bool, enable_f16: bool) -> bool:
    if ("_f32" in symbol) and not enable_f32:
        return False
    if ("_f16" in symbol or "_fp16" in symbol) and not enable_f16:
        return False
    return True


def _defined_archive_symbols(archive: Path) -> set[str]:
    result = subprocess.run(
        ["arm-none-eabi-nm", "--defined-only", str(archive)],
        capture_output=True,
        text=True,
        check=True,
    )
    symbols: set[str] = set()
    for line in result.stdout.splitlines():
        match = _NM_RE.match(line.strip())
        if match is not None:
            symbols.add(match.group(1))
    return symbols


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cmsis-nn-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--archive", type=Path, required=True)
    parser.add_argument("--enable-f32", action="store_true")
    parser.add_argument("--enable-f16", action="store_true")
    args = parser.parse_args()

    headers = [args.cmsis_nn_root / "Include" / "arm_nnfunctions.h"]
    if args.enable_f32 or args.enable_f16:
        headers.append(args.cmsis_nn_root / "Include" / "arm_nnfunctions_flt.h")

    symbols: list[str] = []
    seen: set[str] = set()
    for header in headers:
        for symbol in _collect_symbols(header):
            if not _symbol_enabled(symbol, enable_f32=args.enable_f32, enable_f16=args.enable_f16):
                continue
            if symbol not in seen:
                seen.add(symbol)
                symbols.append(symbol)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    defined_symbols = _defined_archive_symbols(args.archive)

    with args.output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("/* Auto-generated by scripts/generate_kernel_symbol_refs.py */\n")
        retained = [symbol for symbol in symbols if symbol in defined_symbols]
        handle.write(f"/* Retained public API references: {len(retained)} */\n")
        for symbol in retained:
            handle.write(f'{{ "{symbol}", (const void *)(uintptr_t)&{symbol} }},\n')
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
